#!/bin/sh

set -e

MAC_DIR="/data/net-persistent-mac"
INTERFACE="eth0"

mkdir -p "$MAC_DIR"
IF_FILE="$MAC_DIR/$INTERFACE.mac"
IF_MAC="/sys/class/net/$INTERFACE/address"

# Store MAC for reuse
if [ ! -r "$IF_FILE" ]; then
	if [ -e "$IF_MAC" ]; then
		echo "Storing MAC for $INTERFACE for future use."
		cat "$IF_MAC" > "$IF_FILE"
	else
		echo "Failed to read MAC for $INTERFACE; skiping device."
	fi
fi

if [ -r "$IF_FILE" ]; then
	# Restore MAC setting
	WANTED_MAC=`cat $IF_FILE`
	if [ "$WANTED_MAC" != "`cat $IF_MAC`" ]; then
		echo "Setting MAC of $INTERFACE to $WANTED_MAC."
		ifconfig $INTERFACE hw ether "$WANTED_MAC"
	fi
fi
